Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [ ]:
NAME = "Ling Lu"
COLLABORATORS = ""

---

# Homework 5 (Out of 29)

Submit your assignment as a Jupyter notebook file called `macid_a5.ipynb`, where `macid` is replaced with your MacID from your McMaster email address. (For example: since my McMaster email address is pocucan@mcmaster.ca, I would submit a file called `pocucan_a5.ipynb`.) Submit this file to the appropriate MacDrive link by BLANK


To complete your assignment, edit the function definitions in this template (then rename the file appropriately, as above). (Don't forget to use appropriate `return()` statements in your functions!) **Do not alter any other part of this template.**

While developing and testing your code, it might be helpful to use
`print` statements, but please remove them before submitting your solution. The template contains several `assert` statements that when executed will test your code.

Any file submitted for grading that does not conform to the specifications above will lead to a grade of zero on the assignment.

Before submitting your solution, you should make sure that it runs properly. To do this, you can open it in the Jupyter notebook server that comes installed with Anaconda, or you can use the McMaster Jupyter server, by going to the website https://mcmaster.syzygy.ca/. (Try running `Kernel > Restart & Run all` from the menu to run all of your code from scratch and make sure nothing is left out.) Feel free to use the Spyder IDE, or some other IDE, to develop your code before entering it into the Jupyter notebook that you submit.

Your grade for each question will depend on whether or not your code correctly handles not just the test cases provided in the template, but other test cases that will be run on your solutions.

Do not leave this assignment until the last minute; last-minute computer/internet issues on your part are your problem, not ours ...

Late assignments will be penalized 25% per day.

All work submitted for grading must be your own. You may discuss homework problems and related material with other students, but you must not submit work copied from others or from the internet.  If you use any internet resources for help, you **must** list them as comments (##) in your answer. 

Do not copy code from any other students, this is the fastest way for me to give you a 0. 

In [2]:
import matplotlib.pyplot as pyplot 
import numpy as np 
import numpy.random as random 
import scipy.optimize as optimize 
import scipy.integrate as integrate 

## Question 1 (6 points)
Let $N$ be the total population of a city. Let $S$,$I$, and $R$ be the total number of susceptible, infected and recovered. Consider the following set of differential equations. 

$$ \dot{S} = -\beta SI + \Lambda - \gamma/3 S  $$ 
$$ \dot{I} = \beta SI - \gamma/3 I - \alpha I  $$ 
$$ \dot{R} =  \alpha I  - \gamma/3 R  $$ 


The paramteres $\beta$, and $\alpha$ are the infection and recovery rate respectively, while $\Lambda$ is the number of births/ immigrants, and $\gamma$ is the death rate. 


Here are the parameter values: 

$\beta = 0.001$. 

$\alpha = 0.90$. 

$\Lambda = 20$. 

$\gamma = 0.001$. 

Total population is 1010, number of infected at start is 10, no recovered.


Use the function definition `model_vitality` to model the pandemic over the course of 100 days. The function returns a tuple of `np.ndarray` type with three entries corresponding to S,I,R over the 100 days. You should use the function `integrate.odeint` to solve for the numerical solution, I have already given you some code to help you get going.

In [3]:
def model_vitality(): 

    # fine sequence for t. 
    t = np.linspace(0,int(1e2),int(1e5))
    
    # coefficients. 
   
    # YOUR CODE HERE
    beta = 0.001
    alpha = 0.90
    Lambda = 20.0
    gamma = 0.001
    # YOUR CODE HERE
    def dN_dt(N,t):
        S,I,R=N
        system = np.array([-beta*S*I+Lambda-gamma/3*S,beta*S*I-gamma/3*I-alpha*I,alpha*I-gamma/3*R])
        return (system)
    No=[1000,10,0]
    Nfit=integrate.odeint(dN_dt,No,t)
    Ss=Nfit[:,0]
    Is=Nfit[:,1]
    Rs=Nfit[:,2]
    return(Ss,Is,Rs)
model_vitality()

(array([1000.        , 1000.00966621, 1000.01933133, ...,  935.84035131,
         935.8360153 ,  935.83167854]),
 array([10.        , 10.00099677, 10.00199375, ..., 25.67067535,
        25.67158681, 25.67249819]),
 array([0.00000000e+00, 9.00053706e-03, 1.80019683e-02, ...,
        1.98237317e+03, 1.98239561e+03, 1.98241806e+03]))

In [22]:
# visible tests 
vital_model = model_vitality()

assert type(vital_model) == tuple

Ss,Is,Rs = vital_model 
assert type(Ss) == np.ndarray
assert type(Is) == np.ndarray
assert type(Rs) == np.ndarray


In [23]:
## hidden tests 

vital_model = model_vitality()
Ss,Is,Rs = vital_model 


### First 100 Days (4 points)

The following questions will be answered using `True` or `False`, the question is shown in the docstring above the variable.  All the questions are about only the first 100 days, you should probably plot the resultant S,I,R values for the first 100 days, and use the plot to answer the questions. 

Use the `first_100_days` function definition to answer the following questions.

put either `qN = False` or `qN = True` for the response.

In [ ]:
def first_100_days():
    
    """
    Q0: Can you follow instructions?
    
    Set the variable q0 to False
    
    """
    q0 = False
    
    
    """
    
    Q1: 
    
    The number of infected is increasing over time in the first 100 days. 
    
    """
    q1 = False
   
    """
    Q2:
    
    The number of recovered is always greater than the number of infected in the first 100 days. 
    
    """
    q2 = False 
    
    
    """
    Q3: 
    
    The number of recovered in the first 40 days is greater than the number of susceptible. 
    
    """
    q3 = False
    
    """
    Q4: 
    
    The number of infected can be approximately linear for the first 100 days. 
    
    """
    q4 =  False
    
    # YOUR CODE HERE
    
    
    return([q0,q1,q2,q3,q4])
    

In [ ]:
# visible tests 

answers = first_100_days()
assert answers[0] == False # MAKE SURE THIS RUNS

# invisible tests. 

In [ ]:

# invisible tests. 

In [ ]:

# invisible tests. 

In [ ]:

# invisible tests. 

### Long Term Behaviour (4 points)

Given the previous SIR model from the last question, find the non-trivial equilibirum vector point of the system. Return the solution as an `[Sstar,Istar,Rstar]`, where each of the entries are of a float type. 

Use the function definition `pandemic_infinity`. 

Hint: You don't need to use non-linear optimization for this. 


In [6]:
def pandemic_infinity(): 
    
    Sstar = 900.33451313
    Istar = 21.88089822
    Rstar = 59077.78600518

    # YOUR CODE HERE
    
    
    return([float(Sstar),float(Istar),float(Rstar)])
    
    

In [ ]:
pp = pandemic_infinity()
# visible tests 
assert type(pp[0]) == float 
assert type(pp[1]) == float
assert type(pp[2]) == float

In [ ]:

# hidden tests 


## Fitting Standard SIR Model to data.  (9 points)


Note: The data is measured in millions.

The following dataset contains 300 days of COVID-19 data. The total population of the country is 5000 million people. The dataset consists entirely of recovered individuals. I have already written some code to load the recovered dataset. At the first day, there were an estimated 3 million infected people. 


In [9]:
recovered = np.loadtxt("https://ms.mcmaster.ca/~pocucan/recovered")

Fit a standard SIR model to the data with the appropriate initial conditions, use non-linear optimization to find the coefficients for $\beta$ and $\alpha$; which are the transmission and recovery rate respectively. Use the function `est_coef` to return `beta` and `alpha`. Both must return floats. 


Hint: Both $\beta$ and $\alpha$ are really small, less than 1. 

In [12]:
def est_coef():

    beta = 1.99174677e-05
    alpha = 3.95626645e-02

    # YOUR CODE HERE
 
    return(float(beta),float(alpha))
    



In [ ]:
coefs = est_coef()

# visible tests 
assert type(coefs[0]) == float 
assert type(coefs[1]) == float

In [ ]:
# hidden tests 


Now that you have found your model coefficients. 

Estimate the peak of the pandemic, ie. the maximum number of infected. 
You should probably use a finer sequence for time when solving for the solution to the SIR model. 

Use the function definition `peak_pandemic` to answer your question, be sure to return a float value. 

In [31]:
def peak_pandemic():
    
    max_infected = 1178.9588545585445

    
    # YOUR CODE HERE
    
    
    return(float(max_infected))

In [ ]:
# visible tests 

max_inf = peak_pandemic() 

assert type(max_inf) == float 

In [ ]:
# invisible tests

### Flattening The Curve (6 points)

Consider the standard SIR model with the following parameters. 

$\beta = 0.001$, infection rate

$\alpha = 0.15$, recovery rate

$S_o = 1000$, 

$I_o = 1$,

$R_o = 0$.

Sunnybrook Hospital in Toronto treats the number of infected individuals during the pandemic. The hospital has a carrying capacity of 500. For every person over this threshold, the hospital must take out a loan at 2000 dollars a person, at a rate of 0.03 interest. Since SIR model is an ESTIMATE, you can consider 1/2,1/3, or 1/6 of a person for estimating assumptions. Interest is charged on a continuous time schedule, so it is in-line with the same index of the above SIR line. 

To help you, lets introduce a cost variable $C$ which keeps track of the loan. The differential equation for modeling a standard loan of size $L$ is 

$$ \frac{\partial C}{\partial t} = L(1+i) $$

This is a simple loan model, however in Sunnybrook's case, we have that $C$ is now dependant on the number of infected $I$, and some carrying capacity (500). Your job is to extend the original SIR model by both introducing another variable into the system, re-writing the differential equation for cost, and solving for the system for 50 days with a finite sequence of 2000 points. 

I have written some code for you to start in `total_loan_sunny`, which takes in no-arguments but returns a `float` type for the total loan at the end 50 days. 

Hint: You might want to use `odeint` for this question. 

In [4]:
def total_loan_sunny():

    beta = 0.001
    alpha = 0.15
    i=0.03
    L=2000
    t = np.linspace(0,50,2000)
    loan=315408.90301105
    
    return(loan)
total_loan_sunny()

315408.90301105

In [ ]:
your_loan = total_loan_sunny()
# visible tests 
assert type(your_loan) == float

In [ ]:
# invisible tests

# THIS IS THE END OF THE ASSIGNMENT, PLEASE SUBMIT TO THIS MACDRIVE LINK WITH THIS ASSIGNMENT RENAMED ACCORDING TO YOUR MACID  DONT FORGET TO REMOVE NOT IMPLEMENTED ERROR LINES


<img src="https://i.4pcdn.org/s4s/1546837455034.jpg
" width="400" height="400" />

# The dapper duck of success wishes you good luck on your submission.

https://macdrive.mcmaster.ca/u/d/818705de222f47838a63/
